### ISSUE TITLE
crash while rendering overlay

### ISSUE THREAD

**Issue by BugsReporter9000** [lazyMods/Baubles#11]
whenever i try to use a resource pack i get a crash while rendering overlays

crash report:
https://pastebin.com/gKmuZBAz

**Comment by lazynessmind** [comment]
I can't reproduce or crash. Can you send me the modpack and the resource pack so I can test in the same environment?

**Comment by BugsReporter9000** [comment]
the mod pack is : https://www.curseforge.com/minecraft/modpacks/monumental-experience

resource pack : any pack , i tried a bunch of them

**Comment by lazynessmind** [comment]
Hi again. Turn out the problem is being caused by the NoMoWanderer Mod, since wasn't updated to 1.16.4 and the Baubles implementation wasn't done right. To solve the problem I ported the mod to 1.16.4 and fix the error, now he have to wait until the mod author accepts the PR.

All the info is in here: https://github.com/J-Dill/NoMoWanderer/pull/3

**Comment by J-Dill** [comment]
FYI: NoMoWanderer has now been ported to 1.16.4 (thanks to @lazynessmind for the assist)!
